export const IMAGES = {
    REQUEST_BY_LOCATION: 'IMAGES_REQUEST_BY_LOCATION',
    SUCCESS_BY_LOCATION: 'IMAGES_SUCCESS_BY_LOCATION',
    LIKE: 'IMAGE_LIKE'
};

export const POPUPS = {
    OPEN_IMAGE_POPUP: 'POPUPS_OPEN_IMAGE_POPUP',
    CLOSE_IMAGE_POPUP: 'POPUPS_CLOSE_IMAGE_POPUP'
};